create table if not exists public.test_attempts (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete restrict,
  student text not null,
  score integer not null default 0,
  total_questions integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  is_test boolean not null default true,
  created_at timestamptz not null default now(),
  constraint test_attempts_score_nonnegative check (score >= 0),
  constraint test_attempts_total_nonnegative check (total_questions >= 0),
  constraint test_attempts_score_not_over_total check (score <= total_questions)
);

create index if not exists idx_test_attempts_student on public.test_attempts(student);
create index if not exists idx_test_attempts_lesson_id on public.test_attempts(lesson_id);
create index if not exists idx_test_attempts_completed_at on public.test_attempts(completed_at);

create table if not exists public.test_attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.test_attempts(id) on delete cascade,
  question_order integer not null default 0,
  question text not null,
  expected_answer text,
  given_answer text,
  is_correct boolean not null default false,
  question_type text not null default 'text',
  answered_at timestamptz not null default now(),
  constraint test_attempt_answers_order_nonnegative check (question_order >= 0)
);

create index if not exists idx_test_attempt_answers_attempt_id on public.test_attempt_answers(attempt_id);
create index if not exists idx_test_attempt_answers_attempt_order on public.test_attempt_answers(attempt_id, question_order);

alter table public.test_attempts enable row level security;
alter table public.test_attempt_answers enable row level security;

drop policy if exists "Students can create test attempts" on public.test_attempts;
create policy "Students can create test attempts"
on public.test_attempts
for insert
to anon, authenticated
with check (true);

drop policy if exists "Parents can view test attempts" on public.test_attempts;
create policy "Parents can view test attempts"
on public.test_attempts
for select
to authenticated
using (auth.uid() = 'f0f92b9c-5eb7-4b78-aca0-1fea615b1999'::uuid);

drop policy if exists "Students can create test answers" on public.test_attempt_answers;
create policy "Students can create test answers"
on public.test_attempt_answers
for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.test_attempts a
    where a.id = test_attempt_answers.attempt_id
  )
);

drop policy if exists "Parents can view test answers" on public.test_attempt_answers;
create policy "Parents can view test answers"
on public.test_attempt_answers
for select
to authenticated
using (
  exists (
    select 1 from public.test_attempts a
    where a.id = test_attempt_answers.attempt_id
      and auth.uid() = 'f0f92b9c-5eb7-4b78-aca0-1fea615b1999'::uuid
  )
);